# Generated by Django 2.2.3 on 2019-11-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20191113_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
